(() => {
  const KEY='peptivanta-crm-v2';
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const stageNames={new:'新询盘',contacted:'已首次回复',qualifying:'需求确认中',catalog:'已发目录/资料',quoted:'已报价',negotiating:'议价中',payment:'待付款',fulfillment:'已付款/履约',repeat:'待复购/复购'};
  const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return{}}};
  const write=data=>localStorage.setItem(KEY,JSON.stringify(data));
  const today=()=>new Date().toISOString().slice(0,10);
  const tomorrow=()=>{const d=new Date();d.setDate(d.getDate()+1);return d.toISOString().slice(0,10)};
  const teamLabel=x=>x==='美国一组'?'北美组':x;
  const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(n||0));

  function migrateNorthAmerica(){
    if(localStorage.getItem('peptivanta-crm-v8-na')==='1')return false;
    const data=read();if(!data.customers)return false;let changed=false;
    if(Array.isArray(data.teams)){
      const us=data.teams.find(t=>t.name==='美国一组');
      if(us){us.level='一级销售组';changed=true}
      const before=data.teams.length;data.teams=data.teams.filter(t=>t.name!=='加拿大组');if(data.teams.length!==before)changed=true;
    }
    (data.accounts||[]).forEach(a=>{if(a.team==='加拿大组'){a.team='美国一组';changed=true}});
    (data.customers||[]).forEach(c=>{if(c.team==='加拿大组'){c.team='美国一组';changed=true}});
    write(data);localStorage.setItem('peptivanta-crm-v8-na','1');return changed;
  }

  if(migrateNorthAmerica()){location.reload();return}

  const style=document.createElement('style');style.textContent=`
    .v8-detail-panel{margin:0;border-bottom:1px solid #e4e7ec;background:#f8fafc;padding:16px 20px}.v8-detail-panel h3{margin:0 0 12px;font-size:15px}.v8-edit-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.v8-edit-grid label{display:flex;flex-direction:column;gap:5px;font-size:12px;color:#667085}.v8-edit-grid input,.v8-edit-grid select,.v8-edit-grid textarea{width:100%;border:1px solid #d0d5dd;border-radius:5px;padding:9px 10px;background:#fff;font:inherit;color:#1d2939;box-sizing:border-box}.v8-edit-grid textarea{resize:vertical}.v8-span-2{grid-column:span 2}.v8-span-3{grid-column:1/-1}.v8-panel-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:12px}.v8-inline-toolbar{display:flex;gap:8px;flex-wrap:wrap}.v8-order-overlay{position:fixed;inset:0;background:rgba(15,23,42,.42);z-index:1300;display:none;align-items:center;justify-content:center;padding:24px}.v8-order-overlay.open{display:flex}.v8-order-box{width:min(760px,96vw);max-height:90vh;overflow:auto;background:#fff;border-radius:8px;border:1px solid #d0d5dd;box-shadow:0 20px 60px rgba(0,0,0,.18)}.v8-order-head{display:flex;justify-content:space-between;align-items:center;padding:15px 18px;border-bottom:1px solid #e4e7ec}.v8-order-head h2{font-size:17px;margin:0}.v8-order-body{padding:16px 18px}.v8-order-edit{white-space:nowrap}.screenshot-preview{position:relative!important;min-height:330px!important;display:flex!important;align-items:center!important;justify-content:center!important;background:#eef1f5!important;overflow:hidden!important}.screenshot-preview img{display:block!important;max-width:100%!important;max-height:520px!important;width:auto!important;height:auto!important;object-fit:contain!important}.screenshot-preview #v8PreviewLargeBtn{position:absolute;right:10px;bottom:10px}.v8-image-lightbox{position:fixed;inset:0;z-index:1600;background:rgba(0,0,0,.82);display:none;align-items:center;justify-content:center;padding:28px}.v8-image-lightbox.open{display:flex}.v8-image-lightbox img{max-width:95vw;max-height:92vh;object-fit:contain;box-shadow:0 8px 50px rgba(0,0,0,.35)}.v8-image-lightbox button{position:fixed;right:22px;top:18px;width:42px;height:42px;border:0;border-radius:50%;background:#fff;font-size:25px;cursor:pointer}.v8-ocr-assist{margin-top:12px;padding-top:12px;border-top:1px solid #e4e7ec}.v8-ocr-assist label{display:block;font-size:12px;font-weight:600;margin-bottom:6px}.v8-ocr-assist textarea{width:100%;box-sizing:border-box;resize:vertical;border:1px solid #d0d5dd;border-radius:5px;padding:9px;font:inherit}.v8-ocr-assist>div{display:flex;justify-content:flex-end;margin-top:8px}.v8-report-note{font-size:12px;color:#667085;margin:0 14px 10px}.v8-check{display:flex!important;flex-direction:row!important;align-items:center!important;gap:7px!important}.v8-check input{width:auto!important}
    @media(max-width:900px){.v8-edit-grid{grid-template-columns:1fr 1fr}.v8-span-3{grid-column:1/-1}}@media(max-width:620px){.v8-edit-grid{grid-template-columns:1fr}.v8-span-2,.v8-span-3{grid-column:auto}}
  `;document.head.appendChild(style);

  function aliasTeamUI(root=document){
    $$('option',root).forEach(o=>{if(o.value==='美国一组'||o.textContent.trim()==='美国一组'){o.value='美国一组';o.textContent='北美组'}});
    const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);
    nodes.forEach(n=>{const p=n.parentElement;if(!p||['SCRIPT','STYLE','OPTION','TEXTAREA'].includes(p.tagName))return;if(n.nodeValue?.includes('美国一组'))n.nodeValue=n.nodeValue.replaceAll('美国一组','北美组')});
  }
  let aliasQueued=false;new MutationObserver(()=>{if(aliasQueued)return;aliasQueued=true;requestAnimationFrame(()=>{aliasQueued=false;aliasTeamUI(document)})}).observe(document.body,{childList:true,subtree:true});aliasTeamUI(document);

  function ensureOrderModal(){if($('#v8OrderOverlay'))return;const el=document.createElement('div');el.id='v8OrderOverlay';el.className='v8-order-overlay';el.innerHTML=`<div class="v8-order-box"><div class="v8-order-head"><h2>编辑订单</h2><button type="button" class="icon-button" data-v8-order-close>×</button></div><div class="v8-order-body"><form id="v8OrderForm"><input type="hidden" name="id"><div class="v8-edit-grid"><label><span>客户</span><input name="customer" required></label><label><span>负责人</span><input name="owner" required></label><label><span>产品</span><input name="product" required></label><label><span>销售金额 USD</span><input name="amount" type="number" step="0.01" required></label><label><span>成本 USD</span><input name="cost" type="number" step="0.01" required></label><label><span>订单日期</span><input name="date" type="date" required></label><label><span>付款状态</span><select name="payment"><option>待付款</option><option>部分付款</option><option>已付款</option><option>已退款</option></select></label><label><span>物流状态</span><select name="logistics"><option>待发货</option><option>备货中</option><option>已发货</option><option>运输中</option><option>已签收</option><option>异常</option></select></label><label><span>Tracking</span><input name="tracking"></label></div><div class="v8-panel-actions"><button type="button" class="button secondary" data-v8-order-close>取消</button><button class="button primary">保存订单</button></div></form></div></div>`;document.body.appendChild(el);el.addEventListener('click',e=>{if(e.target===el||e.target.closest('[data-v8-order-close]'))el.classList.remove('open')});$('#v8OrderForm').addEventListener('submit',e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget)),data=read(),o=(data.orders||[]).find(x=>x.id===f.id);if(!o)return;o.customer=f.customer;o.owner=f.owner;o.product=f.product;o.amount=Number(f.amount||0);o.cost=Number(f.cost||0);o.payment=f.payment;o.logistics=f.logistics;o.tracking=f.tracking||'—';o.date=f.date;write(data);sessionStorage.setItem('crm-v8-view','orders');location.reload()})}
  function openOrderEditor(id){ensureOrderModal();const data=read(),o=(data.orders||[]).find(x=>x.id===id);if(!o)return;const form=$('#v8OrderForm');for(const [k,v] of Object.entries(o)){const el=form.elements.namedItem(k);if(el)el.value=v??''}$('#v8OrderOverlay').classList.add('open')}
  function enhanceOrders(){const head=$('#view-orders thead tr');if(head&&!head.querySelector('.v8-order-th')){const th=document.createElement('th');th.className='v8-order-th';th.textContent='操作';head.appendChild(th)}$$('#ordersBody tr').forEach(tr=>{if(tr.querySelector('[data-v8-order-edit]'))return;const id=tr.cells[0]?.textContent?.trim();if(!id)return;const td=document.createElement('td');td.innerHTML=`<button type="button" class="button secondary small v8-order-edit" data-v8-order-edit="${esc(id)}">编辑</button>`;tr.appendChild(td)})}
  const ordersBody=$('#ordersBody');if(ordersBody)new MutationObserver(enhanceOrders).observe(ordersBody,{childList:true});enhanceOrders();

  function reportRows(obj,{moneyMode=false}={}){const entries=Object.entries(obj).sort((a,b)=>b[1]-a[1]),max=Math.max(1,...entries.map(x=>x[1]));return entries.map(([k,v])=>`<div class="rank-row"><span>${esc(teamLabel(k))}</span><div class="rank-track"><div class="rank-fill" style="width:${v/max*100}%"></div></div><b>${moneyMode?money(v):v}</b></div>`).join('')||'<div class="workspace-empty" style="height:120px">暂无数据</div>'}
  function renderReportsV8(){const data=read();if(!$('#view-reports'))return;const teams={},stages={},owners={},products={};(data.customers||[]).forEach(c=>{teams[c.team]=(teams[c.team]||0)+Number(c.value||0);stages[stageNames[c.stage]||c.stage]=(stages[stageNames[c.stage]||c.stage]||0)+1;owners[c.owner]=(owners[c.owner]||0)+Number(c.value||0);products[c.product]=(products[c.product]||0)+1});const team=$('#teamPerformance'),stage=$('#sourceChart'),owner=$('#ownerChart'),product=$('#productChart');if(team){team.closest('article').querySelector('h2').textContent='团队机会金额';team.innerHTML=reportRows(teams,{moneyMode:true})}if(stage){stage.closest('article').querySelector('h2').textContent='销售阶段分布';stage.innerHTML=reportRows(stages)}if(owner){owner.closest('article').querySelector('h2').textContent='业务员机会金额';owner.innerHTML=reportRows(owners,{moneyMode:true})}if(product){product.closest('article').querySelector('h2').textContent='产品需求热度';product.innerHTML=Object.entries(products).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="product-chip"><b>${v}</b> · ${esc(k)}</div>`).join('')} }

  function customerById(id){return (read().customers||[]).find(c=>c.id===id)}
  function currentDetailId(){return $('#detailFollowBtn')?.dataset.followCustomer||null}
  function ownerOptions(selected){const data=read();return (data.accounts||[]).filter(a=>a.status==='正常'&&a.displayName!=='Administrator').map(a=>`<option value="${esc(a.displayName)}" ${a.displayName===selected?'selected':''}>${esc(a.displayName)}</option>`).join('')+'<option value="未归属" '+(selected==='未归属'?'selected':'')+'>未归属</option>'}
  function teamOptions(selected){const data=read();return (data.teams||[]).map(t=>`<option value="${esc(t.name)}" ${t.name===selected?'selected':''}>${esc(teamLabel(t.name))}</option>`).join('')+'<option value="—" '+(selected==='—'?'selected':'')+'>—</option>'}
  function typeOptions(selected){return ['个人客户','经销商','零售商','机构采购','科研客户','品牌方','OEM/定制','其他'].map(x=>`<option ${x===selected?'selected':''}>${x}</option>`).join('')}
  function stageOptions(selected){return Object.entries(stageNames).map(([k,v])=>`<option value="${k}" ${k===selected?'selected':''}>${v}</option>`).join('')}
  function gradeOptions(selected){return ['S','A','B','C','D'].map(x=>`<option ${x===selected?'selected':''}>${x}</option>`).join('')}
  function removeDetailPanel(){$('#v8DetailPanel')?.remove()}
  function showCustomerEditor(id){const c=customerById(id);if(!c)return;removeDetailPanel();const panel=document.createElement('div');panel.id='v8DetailPanel';panel.className='v8-detail-panel';panel.innerHTML=`<h3>编辑客户资料</h3><form id="v8CustomerEditForm"><div class="v8-edit-grid"><label><span>客户姓名</span><input name="name" value="${esc(c.name)}" required></label><label><span>国家</span><input name="country" value="${esc(c.country)}" required></label><label><span>联系方式 / WhatsApp</span><input name="contact" value="${esc(c.contact)}"></label><label><span>公司</span><input name="company" value="${esc(c.company)}"></label><label><span>客户类型</span><select name="customerType">${typeOptions(c.customerType)}</select></label><label><span>主要产品</span><input name="product" value="${esc(c.product)}" required></label><label><span>负责人</span><select name="owner">${ownerOptions(c.owner)}</select></label><label><span>所属销售组</span><select name="team">${teamOptions(c.team)}</select></label><label><span>机会金额 USD</span><input name="value" type="number" step="0.01" value="${Number(c.value||0)}"></label><label><span>客户等级</span><select name="grade">${gradeOptions(c.grade)}</select></label><label><span>销售阶段</span><select name="stage">${stageOptions(c.stage)}</select></label><label><span>风险</span><select name="risk"><option ${c.risk==='低'?'selected':''}>低</option><option ${c.risk==='待确认'||c.risk==='待审核'?'selected':''}>待确认</option><option ${c.risk==='高'?'selected':''}>高</option><option ${c.risk==='黑名单'?'selected':''}>黑名单</option></select></label><label class="v8-span-2"><span>标签（逗号分隔）</span><input name="traits" value="${esc((c.traits||[]).join(', '))}"></label><label class="v8-check"><input name="protected" type="checkbox" ${c.protected?'checked':''}><span>保护客户</span></label><label class="v8-span-3"><span>内部备注</span><textarea name="note" rows="3">${esc(c.note||'')}</textarea></label></div><div class="v8-panel-actions"><button type="button" class="button secondary" data-v8-panel-close>取消</button><button class="button primary">保存客户资料</button></div></form>`;$('#detailModalBody').prepend(panel);aliasTeamUI(panel);$('#v8CustomerEditForm').addEventListener('submit',e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget)),data=read(),x=(data.customers||[]).find(y=>y.id===id);if(!x)return;Object.assign(x,{name:f.name,country:f.country,contact:f.contact||'—',company:f.company||'未填写',customerType:f.customerType,product:f.product,owner:f.owner,team:f.owner==='未归属'?'—':f.team,value:Number(f.value||0),grade:f.grade,stage:f.stage,risk:f.risk,note:f.note||'',protected:e.currentTarget.elements.protected.checked,traits:String(f.traits||'').split(',').map(s=>s.trim()).filter(Boolean)});const account=(data.accounts||[]).find(a=>a.displayName===x.owner);if(account?.whatsapp)x.whatsapp=account.whatsapp;write(data);sessionStorage.setItem('crm-v8-reopen',id);location.reload()})}
  function showQuickFollow(id){const c=customerById(id);if(!c)return;removeDetailPanel();const panel=document.createElement('div');panel.id='v8DetailPanel';panel.className='v8-detail-panel';panel.innerHTML=`<h3>直接记录跟进</h3><form id="v8QuickFollowForm"><div class="v8-edit-grid"><label><span>跟进方式</span><select name="channel"><option>WhatsApp</option><option>电话</option><option>邮件</option><option>其他</option></select></label><label><span>跟进类型</span><select name="type"><option>日常跟进</option><option>需求确认</option><option>报价</option><option>议价</option><option>付款</option><option>物流</option><option>售后</option><option>复购</option></select></label><label><span>跟进结果</span><select name="result"><option>继续跟进</option><option>等待客户</option><option>待付款</option><option>已成交</option><option>暂缓</option><option>无效</option></select></label><label class="v8-span-3"><span>本次具体跟进内容</span><textarea name="content" rows="3" required></textarea></label><label class="v8-span-3"><span>客户反馈</span><textarea name="feedback" rows="3" required></textarea></label><label class="v8-span-2"><span>下一步动作</span><input name="nextAction" required></label><label><span>下次跟进日期</span><input name="nextDate" type="date" value="${tomorrow()}" required></label></div><div class="v8-panel-actions"><button type="button" class="button secondary" data-v8-panel-close>取消</button><button class="button primary">保存跟进</button></div></form>`;$('#detailModalBody').prepend(panel);$('#v8QuickFollowForm').addEventListener('submit',e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget)),data=read(),x=(data.customers||[]).find(y=>y.id===id);if(!x)return;x.timeline||=[];x.timeline.unshift({date:today(),channel:f.channel,type:f.type,content:f.content,feedback:f.feedback,nextAction:f.nextAction,nextDate:f.nextDate,author:x.owner||'未归属',result:f.result});x.lastContact=today();x.nextFollowUp=f.nextDate;if(f.result==='待付款')x.stage='payment';if(f.result==='已成交')x.stage='fulfillment';if(f.result==='无效')x.grade='D';write(data);sessionStorage.setItem('crm-v8-reopen',id);location.reload()})}
  function enhanceDetail(){const body=$('#detailModalBody');if(!body||!$('#detailOverlay')?.classList.contains('open'))return;const actions=$('.detail-command-actions',body);if(actions&&!actions.querySelector('[data-v8-edit-customer]')){const id=currentDetailId();if(id){const edit=document.createElement('button');edit.type='button';edit.className='button secondary small';edit.dataset.v8EditCustomer=id;edit.textContent='编辑客户';actions.prepend(edit);const follow=document.createElement('button');follow.type='button';follow.className='button primary small';follow.dataset.v8QuickFollow=id;follow.textContent='直接跟进';actions.appendChild(follow)}}}
  const detailBody=$('#detailModalBody');if(detailBody)new MutationObserver(()=>queueMicrotask(enhanceDetail)).observe(detailBody,{childList:true});

  let lastCustomerId=null,lastClickAt=0;const WINDOW_MS=480;
  document.addEventListener('click',e=>{
    const nav=e.target.closest('[data-view]');if(nav?.dataset.view==='reports')setTimeout(renderReportsV8,20);if(nav?.dataset.view==='orders')setTimeout(enhanceOrders,20);
    const order=e.target.closest('[data-v8-order-edit]');if(order){e.preventDefault();openOrderEditor(order.dataset.v8OrderEdit);return}
    const edit=e.target.closest('[data-v8-edit-customer]');if(edit){e.preventDefault();showCustomerEditor(edit.dataset.v8EditCustomer);return}
    const qf=e.target.closest('[data-v8-quick-follow]');if(qf){e.preventDefault();showQuickFollow(qf.dataset.v8QuickFollow);return}
    if(e.target.closest('[data-v8-panel-close]')){e.preventDefault();removeDetailPanel();return}
    if(e.target.closest('#detailFollowBtn')){const id=currentDetailId();if(id){e.preventDefault();e.stopPropagation();showQuickFollow(id)}return}
    const card=e.target.closest('#customerPool [data-detail-customer]');if(!card||e.target.closest('[data-open-detail]'))return;const id=card.dataset.detailCustomer,now=Date.now();if(id===lastCustomerId&&now-lastClickAt<=WINDOW_MS){lastCustomerId=null;lastClickAt=0;setTimeout(()=>{const fresh=[...document.querySelectorAll('#customerPool [data-detail-customer]')].find(x=>x.dataset.detailCustomer===id);fresh?.querySelector('[data-open-detail]')?.click()},0);return}lastCustomerId=id;lastClickAt=now;
  });

  function restore(){const view=sessionStorage.getItem('crm-v8-view');if(view){sessionStorage.removeItem('crm-v8-view');setTimeout(()=>document.querySelector(`[data-view="${view}"]`)?.click(),50)}const id=sessionStorage.getItem('crm-v8-reopen');if(id){sessionStorage.removeItem('crm-v8-reopen');setTimeout(()=>document.querySelector(`[data-open-detail="${CSS.escape(id)}"]`)?.click(),100)}}
  renderReportsV8();ensureOrderModal();enhanceOrders();enhanceDetail();restore();
})();