(() => {
  const KEY='peptivanta-crm-v2';
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const stageNames={new:'新询盘',contacted:'已首次回复',qualifying:'需求确认中',catalog:'已发目录/资料',quoted:'已报价',negotiating:'议价中',payment:'待付款',fulfillment:'已付款/履约',repeat:'待复购/复购'};
  const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return{}}};
  const write=data=>localStorage.setItem(KEY,JSON.stringify(data));
  const today=()=>new Date().toISOString().slice(0,10);
  const tomorrow=()=>{const d=new Date();d.setDate(d.getDate()+1);return d.toISOString().slice(0,10)};
  const teamLabel=x=>x==='美国一组'?'北美组':x;
  const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(n||0));
  const daysSince=iso=>{if(!iso)return 999;const a=new Date(iso+'T12:00:00'),b=new Date();b.setHours(12,0,0,0);return Math.max(0,Math.round((b-a)/86400000))};

  function migrateNorthAmerica(){
    if(localStorage.getItem('peptivanta-crm-v8-na')==='1')return false;
    const data=read();if(!data.customers)return false;let changed=false;
    if(Array.isArray(data.teams)){
      const us=data.teams.find(t=>t.name==='美国一组');if(us){us.level='一级销售组';changed=true}
      const before=data.teams.length;data.teams=data.teams.filter(t=>t.name!=='加拿大组');if(data.teams.length!==before)changed=true;
    }
    (data.accounts||[]).forEach(a=>{if(a.team==='加拿大组'){a.team='美国一组';changed=true}});
    (data.customers||[]).forEach(c=>{if(c.team==='加拿大组'){c.team='美国一组';changed=true}});
    write(data);localStorage.setItem('peptivanta-crm-v8-na','1');return changed;
  }
  if(migrateNorthAmerica()){location.reload();return}

  const style=document.createElement('style');style.textContent=`
    .v9-detail-panel{margin:0;border-bottom:1px solid #dfe3e8;background:#f7f8fa;padding:18px 20px}.v9-detail-panel h3{margin:0 0 13px;font-size:16px}.v9-edit-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:11px}.v9-edit-grid label{display:flex;flex-direction:column;gap:5px;font-size:12px;color:#667085}.v9-edit-grid input,.v9-edit-grid select,.v9-edit-grid textarea{width:100%;box-sizing:border-box;border:1px solid #cfd5dc;border-radius:5px;padding:10px;background:#fff;font:inherit;color:#1d2939}.v9-edit-grid textarea{resize:vertical}.v9-span-2{grid-column:span 2}.v9-span-3{grid-column:1/-1}.v9-panel-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:14px}.v9-check{display:flex!important;flex-direction:row!important;align-items:center!important;gap:7px!important}.v9-check input{width:auto!important}
    .v9-follow-context{border:1px solid #dfe3e8;background:#fff;padding:12px 14px;margin-bottom:12px;display:grid;grid-template-columns:1.2fr repeat(4,1fr);gap:10px}.v9-follow-context .main strong{display:block;font-size:15px;color:#172033}.v9-follow-context .main span,.v9-follow-context .metric span{display:block;font-size:11px;color:#7b8494;margin-bottom:3px}.v9-follow-context .main small{color:#667085}.v9-follow-context .metric b{font-size:13px;color:#273142}.v9-outcome-bar{display:flex;align-items:center;gap:7px;flex-wrap:wrap;margin:0 0 12px}.v9-outcome-bar>span{font-size:12px;color:#667085;margin-right:3px}.v9-outcome-btn{border:1px solid #cfd5dc;background:#fff;border-radius:4px;padding:7px 10px;font-size:12px;cursor:pointer;color:#344054}.v9-outcome-btn.active{border-color:#315fbd;background:#eef4ff;color:#174ea6;font-weight:600}.v9-outcome-btn.closed.active{border-color:#2e7d50;background:#edf8f1;color:#1f6b43}.v9-outcome-btn.bad.active{border-color:#b54747;background:#fff1f0;color:#a33b3b}.v9-outcome-effect{font-size:12px;line-height:1.55;color:#475467;background:#f3f5f7;border-left:3px solid #98a2b3;padding:8px 10px;margin:0 0 12px}.v9-follow-form .v9-main-input textarea{min-height:86px}.v9-follow-form .v9-feedback textarea{min-height:76px}.v9-follow-help{font-size:11px;color:#8a94a3;margin-top:-1px}.v9-follow-form .form-grid{gap:11px}.v9-follow-form .form-grid label>span{font-weight:600;color:#475467}.v9-follow-form .form-grid textarea,.v9-follow-form .form-grid input,.v9-follow-form .form-grid select{font-size:13px}.v9-follow-form .modal-actions{margin-top:2px}
    .v9-order-overlay{position:fixed;inset:0;background:rgba(15,23,42,.42);z-index:1300;display:none;align-items:center;justify-content:center;padding:24px}.v9-order-overlay.open{display:flex}.v9-order-box{width:min(760px,96vw);max-height:90vh;overflow:auto;background:#fff;border-radius:8px;border:1px solid #d0d5dd;box-shadow:0 20px 60px rgba(0,0,0,.18)}.v9-order-head{display:flex;justify-content:space-between;align-items:center;padding:15px 18px;border-bottom:1px solid #e4e7ec}.v9-order-head h2{font-size:17px;margin:0}.v9-order-body{padding:16px 18px}.v9-order-edit{white-space:nowrap}
    .screenshot-preview{position:relative!important;min-height:330px!important;display:flex!important;align-items:center!important;justify-content:center!important;background:#eef1f5!important;overflow:hidden!important}.screenshot-preview img{display:block!important;max-width:100%!important;max-height:520px!important;width:auto!important;height:auto!important;object-fit:contain!important}
    @media(max-width:900px){.v9-edit-grid{grid-template-columns:1fr 1fr}.v9-span-3{grid-column:1/-1}.v9-follow-context{grid-template-columns:1fr 1fr 1fr}.v9-follow-context .main{grid-column:1/-1}}@media(max-width:620px){.v9-edit-grid{grid-template-columns:1fr}.v9-span-2,.v9-span-3{grid-column:auto}.v9-follow-context{grid-template-columns:1fr 1fr}}
  `;document.head.appendChild(style);

  function aliasTeamUI(root=document){
    $$('option',root).forEach(o=>{if(o.value==='美国一组'||o.textContent.trim()==='美国一组'){o.value='美国一组';o.textContent='北美组'}});
    const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);
    nodes.forEach(n=>{const p=n.parentElement;if(!p||['SCRIPT','STYLE','OPTION','TEXTAREA'].includes(p.tagName))return;if(n.nodeValue?.includes('美国一组'))n.nodeValue=n.nodeValue.replaceAll('美国一组','北美组')});
  }
  let aliasQueued=false;new MutationObserver(()=>{if(aliasQueued)return;aliasQueued=true;requestAnimationFrame(()=>{aliasQueued=false;aliasTeamUI(document)})}).observe(document.body,{childList:true,subtree:true});aliasTeamUI(document);

  function outcomeEffect(result){
    const map={
      '继续跟进':'保留当前阶段；添加“跟进中”，清理已经失效的暂缓标签。',
      '等待客户':'添加“等客户回复”；保留当前销售阶段。',
      '待付款':'销售阶段自动进入“待付款”；标签同步为“待付款”。',
      '已成交':'销售阶段自动进入“已付款/履约”；添加“已成交”，并清理“报价后未回复 / 等客户回复 / 待付款”等过期标签。',
      '暂缓':'添加“暂缓”；保留客户资料和历史，不判定为流失。',
      '无效':'客户等级自动改为 D；添加“无效客户”，清理成交推进类标签。'
    };return map[result]||'';
  }
  function applyOutcome(c,result){
    c.traits=Array.isArray(c.traits)?c.traits:[];
    const remove=(...xs)=>{c.traits=c.traits.filter(t=>!xs.includes(t))};
    const add=x=>{if(x&&!c.traits.includes(x))c.traits.push(x)};
    if(result==='继续跟进'){remove('暂缓','无效客户','已成交','待付款','等客户回复');add('跟进中')}
    if(result==='等待客户'){remove('暂缓','已成交','待付款','跟进中');add('等客户回复')}
    if(result==='待付款'){c.stage='payment';remove('报价后未回复','等客户回复','暂缓','跟进中','已成交');add('待付款')}
    if(result==='已成交'){c.stage='fulfillment';remove('报价后未回复','等客户回复','待付款','暂缓','未回复','跟进中','无效客户');add('已成交')}
    if(result==='暂缓'){remove('等客户回复','待付款','跟进中','已成交');add('暂缓')}
    if(result==='无效'){c.grade='D';remove('报价后未回复','等客户回复','待付款','跟进中','暂缓','已成交');add('无效客户')}
  }
  function activeViewName(){const el=$('.view.active');return el?.id?.replace('view-','')||'dashboard'}
  function saveFollowRecord(payload,{reopenId=null}={}){
    const data=read(),c=(data.customers||[]).find(x=>x.id===payload.customerId);if(!c)return false;
    c.timeline=Array.isArray(c.timeline)?c.timeline:[];
    c.timeline.unshift({date:today(),channel:payload.channel,type:payload.type,content:payload.content,feedback:payload.feedback,nextAction:payload.nextAction,nextDate:payload.nextDate,author:payload.author||c.owner||'未归属',result:payload.result,objection:payload.objection||''});
    c.lastContact=today();c.nextFollowUp=payload.nextDate;applyOutcome(c,payload.result);write(data);
    sessionStorage.setItem('crm-v9-view',activeViewName());if(reopenId)sessionStorage.setItem('crm-v9-reopen',reopenId);
    location.reload();return true;
  }

  function customerContextHtml(c){return `<div class="v9-follow-context"><div class="main"><span>当前客户</span><strong>${esc(c?.name||'未选择')}</strong><small>${esc(c?.product||'')} · ${esc(c?.country||'')}</small></div><div class="metric"><span>销售阶段</span><b>${esc(stageNames[c?.stage]||c?.stage||'—')}</b></div><div class="metric"><span>客户等级</span><b>${esc(c?.grade||'—')}</b></div><div class="metric"><span>距上次跟进</span><b>${c?daysSince(c.lastContact)+' 天':'—'}</b></div><div class="metric"><span>负责人</span><b>${esc(c?.owner||'—')}</b></div></div>`}
  function outcomeBarHtml(selected='继续跟进'){const opts=['继续跟进','等待客户','待付款','已成交','暂缓','无效'];return `<div class="v9-outcome-bar"><span>快速结果</span>${opts.map(x=>`<button type="button" class="v9-outcome-btn ${x===selected?'active':''} ${x==='已成交'?'closed':''} ${x==='无效'?'bad':''}" data-v9-outcome="${x}">${x}</button>`).join('')}</div><div class="v9-outcome-effect" data-v9-outcome-effect>${outcomeEffect(selected)}</div>`}
  function obstructionOptions(){return `<option>无明显阻力</option><option>价格</option><option>MOQ / 数量</option><option>规格</option><option>COA / 检测文件</option><option>物流 / 时效</option><option>付款方式</option><option>等待客户内部确认</option><option>竞争供应商</option><option>其他</option>`}

  function rebuildMainFollowForm(){
    const form=$('#followForm');if(!form||form.dataset.v9Built==='1')return;form.dataset.v9Built='1';form.classList.add('v9-follow-form');
    form.innerHTML=`<div id="v9MainFollowContext"></div>${outcomeBarHtml('继续跟进')}<div class="form-grid"><label><span>客户 *</span><select name="customerId" id="followCustomerSelect" required></select></label><label><span>跟进方式</span><select name="channel"><option>WhatsApp</option><option>电话</option><option>邮件</option><option>其他</option></select></label><label><span>跟进类型</span><select name="type"><option>日常跟进</option><option>需求确认</option><option>报价</option><option>议价</option><option>付款</option><option>物流</option><option>售后</option><option>复购</option></select></label><label><span>记录人</span><select name="author" id="followAuthorSelect"></select></label><label><span>当前主要阻力</span><select name="objection">${obstructionOptions()}</select></label><label><span>跟进结果</span><select name="result"><option>继续跟进</option><option>等待客户</option><option>待付款</option><option>已成交</option><option>暂缓</option><option>无效</option></select></label><label class="span-2 v9-main-input"><span>本次做了什么 / 发了什么 *</span><textarea name="content" rows="4" required placeholder="例：发送 Tirzepatide 10mg 报价和 COA；确认首批数量与收货国家。"></textarea><small class="v9-follow-help">只记录事实：发了什么、问了什么、确认了什么。</small></label><label class="span-2 v9-feedback"><span>客户反馈 / 原话 *</span><textarea name="feedback" rows="3" required placeholder="例：价格可以接受，但需要先和合伙人确认数量；预计明天回复。"></textarea></label><label class="span-2"><span>下一步动作 *</span><input name="nextAction" required placeholder="例：明天下午确认数量；若确认则发送最终 PI / 付款信息。"></label><label><span>下次跟进日期 *</span><input type="date" name="nextDate" value="${tomorrow()}" required></label></div><div class="modal-actions"><button type="button" class="button secondary" data-close-modal>取消</button><button class="button primary">保存跟进记录</button></div>`;
    form.addEventListener('submit',e=>{e.preventDefault();e.stopImmediatePropagation();const f=Object.fromEntries(new FormData(form));saveFollowRecord(f,{reopenId:null})},true);
    form.addEventListener('change',e=>{if(e.target.name==='customerId')refreshMainFollowContext();if(e.target.name==='result')syncOutcomeUI(form,e.target.value)});
    form.addEventListener('click',e=>{const b=e.target.closest('[data-v9-outcome]');if(!b)return;form.elements.result.value=b.dataset.v9Outcome;syncOutcomeUI(form,b.dataset.v9Outcome)});
  }
  function syncOutcomeUI(root,result){$$('[data-v9-outcome]',root).forEach(b=>b.classList.toggle('active',b.dataset.v9Outcome===result));const effect=$('[data-v9-outcome-effect]',root);if(effect)effect.textContent=outcomeEffect(result)}
  function refreshMainFollowContext(){const form=$('#followForm'),box=$('#v9MainFollowContext');if(!form||!box)return;const data=read(),id=form.elements.customerId?.value,c=(data.customers||[]).find(x=>x.id===id);box.innerHTML=customerContextHtml(c);aliasTeamUI(box)}

  function ensureOrderModal(){if($('#v9OrderOverlay'))return;const el=document.createElement('div');el.id='v9OrderOverlay';el.className='v9-order-overlay';el.innerHTML=`<div class="v9-order-box"><div class="v9-order-head"><h2>编辑订单</h2><button type="button" class="icon-button" data-v9-order-close>×</button></div><div class="v9-order-body"><form id="v9OrderForm"><input type="hidden" name="id"><div class="v9-edit-grid"><label><span>客户</span><input name="customer" required></label><label><span>负责人</span><input name="owner" required></label><label><span>产品</span><input name="product" required></label><label><span>销售金额 USD</span><input name="amount" type="number" step="0.01" required></label><label><span>成本 USD</span><input name="cost" type="number" step="0.01" required></label><label><span>订单日期</span><input name="date" type="date" required></label><label><span>付款状态</span><select name="payment"><option>待付款</option><option>部分付款</option><option>已付款</option><option>已退款</option></select></label><label><span>物流状态</span><select name="logistics"><option>待发货</option><option>备货中</option><option>已发货</option><option>运输中</option><option>已签收</option><option>异常</option></select></label><label><span>Tracking</span><input name="tracking"></label></div><div class="v9-panel-actions"><button type="button" class="button secondary" data-v9-order-close>取消</button><button class="button primary">保存订单</button></div></form></div></div>`;document.body.appendChild(el);el.addEventListener('click',e=>{if(e.target===el||e.target.closest('[data-v9-order-close]'))el.classList.remove('open')});$('#v9OrderForm').addEventListener('submit',e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget)),data=read(),o=(data.orders||[]).find(x=>x.id===f.id);if(!o)return;o.customer=f.customer;o.owner=f.owner;o.product=f.product;o.amount=Number(f.amount||0);o.cost=Number(f.cost||0);o.payment=f.payment;o.logistics=f.logistics;o.tracking=f.tracking||'—';o.date=f.date;write(data);sessionStorage.setItem('crm-v9-view','orders');location.reload()})}
  function openOrderEditor(id){ensureOrderModal();const data=read(),o=(data.orders||[]).find(x=>x.id===id);if(!o)return;const form=$('#v9OrderForm');for(const [k,v] of Object.entries(o)){const el=form.elements.namedItem(k);if(el)el.value=v??''}$('#v9OrderOverlay').classList.add('open')}
  function enhanceOrders(){const head=$('#view-orders thead tr');if(head&&!head.querySelector('.v9-order-th')){const th=document.createElement('th');th.className='v9-order-th';th.textContent='操作';head.appendChild(th)}$$('#ordersBody tr').forEach(tr=>{if(tr.querySelector('[data-v9-order-edit]'))return;const id=tr.cells[0]?.textContent?.trim();if(!id)return;const td=document.createElement('td');td.innerHTML=`<button type="button" class="button secondary small v9-order-edit" data-v9-order-edit="${esc(id)}">编辑</button>`;tr.appendChild(td)})}
  const ordersBody=$('#ordersBody');if(ordersBody)new MutationObserver(enhanceOrders).observe(ordersBody,{childList:true});enhanceOrders();

  function reportRows(obj,{moneyMode=false}={}){const entries=Object.entries(obj).sort((a,b)=>b[1]-a[1]),max=Math.max(1,...entries.map(x=>x[1]));return entries.map(([k,v])=>`<div class="rank-row"><span>${esc(teamLabel(k))}</span><div class="rank-track"><div class="rank-fill" style="width:${v/max*100}%"></div></div><b>${moneyMode?money(v):v}</b></div>`).join('')||'<div class="workspace-empty" style="height:120px">暂无数据</div>'}
  function renderReportsV9(){const data=read();if(!$('#view-reports'))return;const teams={},stages={},owners={},products={};(data.customers||[]).forEach(c=>{teams[c.team]=(teams[c.team]||0)+Number(c.value||0);stages[stageNames[c.stage]||c.stage]=(stages[stageNames[c.stage]||c.stage]||0)+1;owners[c.owner]=(owners[c.owner]||0)+Number(c.value||0);products[c.product]=(products[c.product]||0)+1});const team=$('#teamPerformance'),stage=$('#sourceChart'),owner=$('#ownerChart'),product=$('#productChart');if(team){team.closest('article').querySelector('h2').textContent='团队机会金额';team.innerHTML=reportRows(teams,{moneyMode:true})}if(stage){stage.closest('article').querySelector('h2').textContent='销售阶段分布';stage.innerHTML=reportRows(stages)}if(owner){owner.closest('article').querySelector('h2').textContent='业务员机会金额';owner.innerHTML=reportRows(owners,{moneyMode:true})}if(product){product.closest('article').querySelector('h2').textContent='产品需求热度';product.innerHTML=Object.entries(products).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="product-chip"><b>${v}</b> · ${esc(k)}</div>`).join('')}}

  function customerById(id){return (read().customers||[]).find(c=>c.id===id)}
  function currentDetailId(){return $('#detailFollowBtn')?.dataset.followCustomer||null}
  function ownerOptions(selected){const data=read();return (data.accounts||[]).filter(a=>a.status==='正常'&&a.displayName!=='Administrator').map(a=>`<option value="${esc(a.displayName)}" ${a.displayName===selected?'selected':''}>${esc(a.displayName)}</option>`).join('')+'<option value="未归属" '+(selected==='未归属'?'selected':'')+'>未归属</option>'}
  function teamOptions(selected){const data=read();return (data.teams||[]).map(t=>`<option value="${esc(t.name)}" ${t.name===selected?'selected':''}>${esc(teamLabel(t.name))}</option>`).join('')+'<option value="—" '+(selected==='—'?'selected':'')+'>—</option>'}
  function typeOptions(selected){return ['个人客户','经销商','零售商','机构采购','科研客户','品牌方','OEM/定制','其他'].map(x=>`<option ${x===selected?'selected':''}>${x}</option>`).join('')}
  function stageOptions(selected){return Object.entries(stageNames).map(([k,v])=>`<option value="${k}" ${k===selected?'selected':''}>${v}</option>`).join('')}
  function gradeOptions(selected){return ['S','A','B','C','D'].map(x=>`<option ${x===selected?'selected':''}>${x}</option>`).join('')}
  function removeDetailPanel(){$('#v9DetailPanel')?.remove()}
  function showCustomerEditor(id){const c=customerById(id);if(!c)return;removeDetailPanel();const panel=document.createElement('div');panel.id='v9DetailPanel';panel.className='v9-detail-panel';panel.innerHTML=`<h3>编辑客户资料</h3><form id="v9CustomerEditForm"><div class="v9-edit-grid"><label><span>客户姓名</span><input name="name" value="${esc(c.name)}" required></label><label><span>国家</span><input name="country" value="${esc(c.country)}" required></label><label><span>联系方式 / WhatsApp</span><input name="contact" value="${esc(c.contact)}"></label><label><span>公司</span><input name="company" value="${esc(c.company)}"></label><label><span>客户类型</span><select name="customerType">${typeOptions(c.customerType)}</select></label><label><span>主要产品</span><input name="product" value="${esc(c.product)}" required></label><label><span>负责人</span><select name="owner">${ownerOptions(c.owner)}</select></label><label><span>所属销售组</span><select name="team">${teamOptions(c.team)}</select></label><label><span>机会金额 USD</span><input name="value" type="number" step="0.01" value="${Number(c.value||0)}"></label><label><span>客户等级</span><select name="grade">${gradeOptions(c.grade)}</select></label><label><span>销售阶段</span><select name="stage">${stageOptions(c.stage)}</select></label><label><span>风险</span><select name="risk"><option ${c.risk==='低'?'selected':''}>低</option><option ${c.risk==='待确认'||c.risk==='待审核'?'selected':''}>待确认</option><option ${c.risk==='高'?'selected':''}>高</option><option ${c.risk==='黑名单'?'selected':''}>黑名单</option></select></label><label class="v9-span-2"><span>标签（逗号分隔）</span><input name="traits" value="${esc((c.traits||[]).join(', '))}"></label><label class="v9-check"><input name="protected" type="checkbox" ${c.protected?'checked':''}><span>保护客户</span></label><label class="v9-span-3"><span>内部备注</span><textarea name="note" rows="3">${esc(c.note||'')}</textarea></label></div><div class="v9-panel-actions"><button type="button" class="button secondary" data-v9-panel-close>取消</button><button class="button primary">保存客户资料</button></div></form>`;$('#detailModalBody').prepend(panel);aliasTeamUI(panel);$('#v9CustomerEditForm').addEventListener('submit',e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget)),data=read(),x=(data.customers||[]).find(y=>y.id===id);if(!x)return;Object.assign(x,{name:f.name,country:f.country,contact:f.contact||'—',company:f.company||'未填写',customerType:f.customerType,product:f.product,owner:f.owner,team:f.owner==='未归属'?'—':f.team,value:Number(f.value||0),grade:f.grade,stage:f.stage,risk:f.risk,note:f.note||'',protected:e.currentTarget.elements.protected.checked,traits:String(f.traits||'').split(',').map(s=>s.trim()).filter(Boolean)});const account=(data.accounts||[]).find(a=>a.displayName===x.owner);if(account?.whatsapp)x.whatsapp=account.whatsapp;write(data);sessionStorage.setItem('crm-v9-reopen',id);location.reload()})}
  function showQuickFollow(id){const c=customerById(id);if(!c)return;removeDetailPanel();const panel=document.createElement('div');panel.id='v9DetailPanel';panel.className='v9-detail-panel';panel.innerHTML=`<h3>记录客户跟进</h3><form id="v9QuickFollowForm" class="v9-follow-form">${customerContextHtml(c)}${outcomeBarHtml('继续跟进')}<div class="v9-edit-grid"><label><span>跟进方式</span><select name="channel"><option>WhatsApp</option><option>电话</option><option>邮件</option><option>其他</option></select></label><label><span>跟进类型</span><select name="type"><option>日常跟进</option><option>需求确认</option><option>报价</option><option>议价</option><option>付款</option><option>物流</option><option>售后</option><option>复购</option></select></label><label><span>跟进结果</span><select name="result"><option>继续跟进</option><option>等待客户</option><option>待付款</option><option>已成交</option><option>暂缓</option><option>无效</option></select></label><label><span>当前主要阻力</span><select name="objection">${obstructionOptions()}</select></label><label class="v9-span-3 v9-main-input"><span>本次做了什么 / 发了什么 *</span><textarea name="content" rows="3" required placeholder="例：发送报价和 COA；确认首批数量与收货国家。"></textarea></label><label class="v9-span-3 v9-feedback"><span>客户反馈 / 原话 *</span><textarea name="feedback" rows="3" required placeholder="例：价格可以接受，但需要先确认数量，预计明天回复。"></textarea></label><label class="v9-span-2"><span>下一步动作 *</span><input name="nextAction" required placeholder="例：明天下午确认数量；确认后发送最终付款信息。"></label><label><span>下次跟进日期 *</span><input name="nextDate" type="date" value="${tomorrow()}" required></label></div><div class="v9-panel-actions"><button type="button" class="button secondary" data-v9-panel-close>取消</button><button class="button primary">保存跟进</button></div></form>`;$('#detailModalBody').prepend(panel);const form=$('#v9QuickFollowForm');form.addEventListener('click',e=>{const b=e.target.closest('[data-v9-outcome]');if(!b)return;form.elements.result.value=b.dataset.v9Outcome;syncOutcomeUI(form,b.dataset.v9Outcome)});form.elements.result.addEventListener('change',()=>syncOutcomeUI(form,form.elements.result.value));form.addEventListener('submit',e=>{e.preventDefault();const f=Object.fromEntries(new FormData(form));f.customerId=id;f.author=c.owner||'未归属';saveFollowRecord(f,{reopenId:id})})}
  function enhanceDetail(){const body=$('#detailModalBody');if(!body||!$('#detailOverlay')?.classList.contains('open'))return;const actions=$('.detail-command-actions',body);if(actions&&!actions.querySelector('[data-v9-edit-customer]')){const id=currentDetailId();if(id){const edit=document.createElement('button');edit.type='button';edit.className='button secondary small';edit.dataset.v9EditCustomer=id;edit.textContent='编辑客户';actions.prepend(edit);const follow=document.createElement('button');follow.type='button';follow.className='button primary small';follow.dataset.v9QuickFollow=id;follow.textContent='记录跟进';actions.appendChild(follow)}}}
  const detailBody=$('#detailModalBody');if(detailBody)new MutationObserver(()=>queueMicrotask(enhanceDetail)).observe(detailBody,{childList:true});

  // Stable single/double-click handling for customer pool. First click is delayed briefly so the DOM is not rebuilt before a second click arrives.
  let pendingId=null,pendingAt=0,pendingTimer=null;const DOUBLE_MS=420,SINGLE_DELAY=250;
  function releaseSingle(id){const fresh=[...document.querySelectorAll('#customerPool [data-detail-customer]')].find(x=>x.dataset.detailCustomer===id);if(!fresh)return;const ev=new MouseEvent('click',{bubbles:true,cancelable:true,view:window});ev.__v9Pass=true;fresh.dispatchEvent(ev)}
  document.addEventListener('click',e=>{
    if(e.__v9Pass)return;
    const card=e.target.closest('#customerPool [data-detail-customer]');if(!card||e.target.closest('[data-open-detail]'))return;
    e.preventDefault();e.stopImmediatePropagation();const id=card.dataset.detailCustomer,now=Date.now();
    if(pendingId===id&&now-pendingAt<=DOUBLE_MS){clearTimeout(pendingTimer);pendingTimer=null;pendingId=null;pendingAt=0;card.querySelector('[data-open-detail]')?.click();return}
    if(pendingTimer){clearTimeout(pendingTimer);const old=pendingId;pendingTimer=null;pendingId=null;if(old)releaseSingle(old)}
    pendingId=id;pendingAt=now;pendingTimer=setTimeout(()=>{const x=pendingId;pendingId=null;pendingAt=0;pendingTimer=null;if(x)releaseSingle(x)},SINGLE_DELAY)
  },true);
  document.addEventListener('dblclick',e=>{const card=e.target.closest('#customerPool [data-detail-customer]');if(card){e.preventDefault();e.stopImmediatePropagation()}},true);

  document.addEventListener('click',e=>{
    const nav=e.target.closest('[data-view]');if(nav?.dataset.view==='reports')setTimeout(renderReportsV9,20);if(nav?.dataset.view==='orders')setTimeout(enhanceOrders,20);
    const order=e.target.closest('[data-v9-order-edit]');if(order){e.preventDefault();openOrderEditor(order.dataset.v9OrderEdit);return}
    const edit=e.target.closest('[data-v9-edit-customer]');if(edit){e.preventDefault();showCustomerEditor(edit.dataset.v9EditCustomer);return}
    const qf=e.target.closest('[data-v9-quick-follow]');if(qf){e.preventDefault();showQuickFollow(qf.dataset.v9QuickFollow);return}
    if(e.target.closest('[data-v9-panel-close]')){e.preventDefault();removeDetailPanel();return}
    if(e.target.closest('#detailFollowBtn')){const id=currentDetailId();if(id){e.preventDefault();e.stopPropagation();showQuickFollow(id)}return}
    if(e.target.closest('#quickFollowBtn')||e.target.closest('[data-follow-customer]'))setTimeout(()=>{rebuildMainFollowForm();refreshMainFollowContext()},20);
  });

  function restore(){const view=sessionStorage.getItem('crm-v9-view');if(view){sessionStorage.removeItem('crm-v9-view');setTimeout(()=>document.querySelector(`[data-view="${view}"]`)?.click(),60)}const id=sessionStorage.getItem('crm-v9-reopen');if(id){sessionStorage.removeItem('crm-v9-reopen');setTimeout(()=>document.querySelector(`[data-open-detail="${CSS.escape(id)}"]`)?.click(),130)}}
  rebuildMainFollowForm();renderReportsV9();ensureOrderModal();enhanceOrders();enhanceDetail();restore();
})();